### ISSUE TITLE
Presence of node_modules disables type checking based on lib definitions

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#447]
If I have a project like so:
```
- .flowconfig
- index.js
- lib/
  - rx.js
- node_modules/
  - rx/**/*
```

With the following properties:

1. `.flowconfig` sets `[lib]` to `./lib`.
2. `lib/rx.js` contains:

        type rx$Observable<T> = {
          subscribeOnNext(f: (x: T) => void): rx$Disposable
        }

        type rx$Observer<T> = {
          onNext(x: T): void
        }

        type rx$Disposable = {
          dispose(): void
        }

        type rx$Observable$static = {
          create<T>(f: (observer: rx$Observer<T>) => rx$Disposable): rx$Observable<T>
        }

        declare module "rx" {
          declare var Observable: rx$Observable$static;
        }

3. `index.js` contains:

        /* @flow */

        import { Observable } from "rx"

        var test = Observable.create()

Then I expect `flow check` to complain.

```
index.js:5:12,30: call of method create
Too few arguments (expected default/rest parameters in function)
lib/rx.js:14:3,77: function type
```

However, as long as `node_modules/rx` exists, flow is silent. Only if I remove the `node_modules/rx` folder does flow start to consider the definitions in `lib`.

**Comment by mindeavor** [comment]
Any updates on this? This makes it difficult to use with browserify, especially since my computer is somewhat slow to parse read everything in `node_modules/`.

**Comment by jeffmo** [comment]
This seems to be as simple as the fact that flow gives node_modules packages preference over library module declarations. Of course this seems wrong to me, so going to chat with @bhosmer to see if there's a solid reason we do this.

If not, I think it makes a lot of sense to make library definitions trump actual modules

**Comment by samwgoldman** [comment]
In a perfect world, I'd like flow to combine the inferred types with the declared types.

For example, if I write a declaration for a function that *actually* returns `?string`, but I write `string`, it would be great if flow could tell me. That is, I would want flow to check that the inferred types can flow into the declared types.

I'm not sure that's realistic right now, but if it's possible to set up, I'd be willing to test it out with a few in-the-wild libraries.

**Comment by danvk** [comment]
I'll close out #557 as a dupe, but a few highlights: it has a fairly simple repro, and this seems to have regressed between Flow 0.9 and 0.10.

**Comment by danvk** [comment]
@jeffmo Any update on this? Your solution (changing precedence) sounds reasonable to me.

It would be really nice to use third-party libraries with Flow again.

**Comment by jeffmo** [comment]
We just talked this through and I think @mroch is going to take point on this

**Comment by samwgoldman** [comment]
:sparkles: :raised_hands:  :sparkles:

**Comment by bhosmer** [comment]
Quick status on this.: after some discussion we think the real solution is essentially Sam's "perfect world" if both a declaration and an implementation resolve to the same name, they should be checked for consistency. 

For situations when both are present Avik's mental model works nicely, which is basically a Russian doll with the implementation (the code in the module) at the center, wrapped with layers of signature: first the one that the implementation is exported with, and then, possibly, a library declaration. Users only see the outermost layer, but they all have to agree. This naturally handles the usual cases:

1. checked source module (`@flow`)
2. unchecked source module (no `@flow`, exported sig = `any`)
3. library decl only
4. library decl + checked source module
5. library decl + unchecked source module

In particular, case 5 works because the unchecked module's export sig agrees with anything, including the signature provided by the declaration.

That's the real solution, but it may not appear instantly, so we want to make sure there's a way to work around the issue in the meantime. I did #557 (thanks @danvk for the easy repro!) and then tried to [ignore] underscore and ran into an infuriating catch-22 around `package.json` not getting ignored properly :( but assuming that can be fixed quickly (I'm sure it can), would [ignore] would be a short-term workaround, or am I overlooking other issues there?

The fallback short-term idea is to mess with the lookup ordering so that unchecked (non-`@flow`) files fall behind library files in the lookup precedence, but we'd rather avoid the NRE if we don't need it, given the longer-term setup we're aiming for. 

cc @mroch who's the other Flow guy digging into this.

**Comment by samwgoldman** [comment]
Fixing the ignore/package.json catch-22 would be a great interim solution, IMHO. Very glad to see movement on this issue!

**Comment by bhosmer** [comment]
FYI the ignore package.json thing is fixed in https://github.com/facebook/flow/commit/adc11907a3dad6ce7ddde8b710805b2306e75c16 :)

**Comment by garetht** [comment]
Thanks for the workaround!

**Comment by danvk** [comment]
So the workaround here is to explicitly add `node_modules/underscore` to the `[ignore]` section if I want to use an external type definitions file with it?

**Comment by aidanhs** [comment]
It seems you can also trigger an internal error by selectively and omitting some packages from includes. E.g.:
```
$ cd $(mktemp -d)
$ npm install flow-bin react
[...]
$ mkdir src
$ echo -e '/* @flow */\nrequire("react");' > src/t.js
$ touch src/.flowconfig
$ ./node_modules/.bin/flow check src/
/tmp/tmp.wtxDEO6YXo/src/t.js: 
Failure("internal error: package /tmp/tmp.wtxDEO6YXo/node_modules/react/package.json not found")

Found 1 error
```

Note that this also happens on master, i.e. it's not fixed by https://github.com/facebook/flow/issues/447#issuecomment-117441832

**Comment by danvk** [comment]
This seems to be fixed in Flow 0.14.0. For those following along at home, this will produce an error:

```javascript
// foo.js
/** @flow */
var _ = require('underscore');

function foo(): string {
  var x = _.clone("foo");  // ok
  return _.foo();  // call of method foo Property not found in module underscore
}
```

```
// .flowconfig
[ignore]
.*node_modules/flow-bin.*
.*node_modules/underscore.*

[include]

[libs]
lib

[options]
```

```
// lib/underscore.js
declare module "underscore" {
  declare function findWhere<T>(list: Array<T>, properties: {}): ?T;
  declare function clone<T>(obj: T): T;
  // ...
}
```

Putting `node_modules/underscore` in the `[ignore]` section of your `.flowconfig` is required. If you don't, you won't see any errors relating to underscore.

**Comment by gabelevi** [comment]
@jeffmo is working on handling the case where we have both a lib definition and the implementation for some module. We're going to track that with https://github.com/facebook/flow/issues/676
