### ISSUE TITLE
Support require which returns `any` if flow lost it

### ISSUE THREAD

**Issue by mizchi** [facebook/flow#51]
I want to ignore `Required module not found` and load it as `any`.
Type checking to extenal libraries are not serious problem.

I tried this

```
declare require: (s: string) => any;
```

but it overrides all require and lost other info.

**Comment by iammerrick** [comment]
@tcoopman Can this be "resolved" with an ignore of all files ending in css or a particular extension?

**Comment by iammerrick** [comment]
@avikchaudhuri See above comment :-)

**Comment by gaearon** [comment]
+1. This is currently my blocker for Flow.

**Comment by tcoopman** [comment]
Mine too. Maybe some way to tell flow that a type is what it is and that it should not check it any further?

```js
var image: !string = require('image.jpg');
var css: !any = require('main.css');
```

Comparable with maybe types, but instead of `?` you add `!`. This doesn't let you do `require('./Activity.less');` though, so maybe the suggestion of @gaearon is still necessary unless you could do: `reauire('./Activity.less'): !any`

**Comment by arypurnomoz** [comment]
+1

**Comment by syranide** [comment]
+1

**Comment by thealjey** [comment]
+1

**Comment by williamfligor** [comment]
+1

**Comment by gcazaciuc** [comment]
+1

**Comment by nktpro** [comment]
+1

**Comment by syranide** [comment]
Perhaps the proper approach is to actually have an intermediate step where autogenerated files are output instead, so that flow can parse them. I'd imagine there are a bunch of benefits to it not only being part of the final bundling process.

**Comment by tcoopman** [comment]
@syranide not sure what you mean. You mean that flow should parse the css or url?

**Comment by syranide** [comment]
@tcoopman Rather than webpack (etc) generating js-files for css-files/etc only at the final bundle-stage, being able to output them to disk could make sense, then flow would have access to all the js-files it needs, no workarounds necessary. This would be useful for making many other transforms compatible with flow as well.

**Comment by tcoopman** [comment]
@syranide ok I see. That would be nice but it also seems that would need more support from the build tools?
Wouldn't you then also need to transform your original files or create a mapping file so flow knows where to find them?

So

`var f = require(file.jpg)`
Outputs file.jpg minimised and hashed filename + a is file that has the hashed filename.

After the translation it would be `var f = 'file.hash.jpg'` and flow could type check that.

Again seems nice but in the meantime a solution where you can tell flow that a variable is of a type without type checking it would be a good start.

**Comment by syranide** [comment]
@tcoopman It wouldn't necessarily need more support from the build tools, but some of the steps would have to be available separately (either by the bundler or by an entirely separate transform tool, which seems preferable).

> Wouldn't you then also need to transform your original files or create a mapping file so flow knows where to find them?

`require('app.css')` would generate `app.css.js` according to some user specified css transform (which it already does, it just does so internally), so the initial require would still work as-is. If you had some non-standard require resolution (say `@providesModule`) then it could also be applied in this step, flattening the files and rewriting the `require`s.

A nice side-effect is that this would also be compatible with any bundler, so you're less committed to any one bundler and can more easily switch if the need arises.

**Comment by tcoopman** [comment]
@syranide that looks like it could work indeed. I've asked @sokra on gitter to give his opinion about this.

**Comment by sokra** [comment]
> `require('app.css')` would generate `app.css.js`

Workaround and too error prone.

---

We could implement a webpack output mode, which outputs every module as separate js file and generate node.js `require`s. Basically compiling to a node.js app containing multiple files.

---

Or we could generate a bundle that can be parsed by flow. SourceMaps could be used to map errors back to the original sources...

**Comment by samwgoldman** [comment]
Each example given in this issue deals with requiring non-JS files, which I believe can now be handled using the `module.name_mapper` config with a declaration file. See #345, #382, and the [commit message for the fix](https://github.com/facebook/flow/commit/625c25ae5d7c429cf4f7191bc3a8e948623d271d), which goes into a bit more usage detail.

Does anyone have a use case that isn't addressed with `module.name_mapper`?

**Comment by frederickfogerty** [comment]
@samwgoldman do you have an example of how it would work for css files?

**Comment by matthewoates** [comment]
+1

**Comment by jeffutter** [comment]
I imagine this would work by including something like:

```module.name_mapper= '.*\.s*css$' -> './CSSStub'```

in your config and then declaring a module like this:

```declare module CSSStub {
}```

But I still get errors like this:
```admin.js:8:1,41: sweetalert/dev/sweetalert.scss
Required module not found```

I'm probably overlooking something simple, any advice?

**Comment by samwgoldman** [comment]
I recently saw someone post a [complete example](https://gist.github.com/lambdahands/d19e0da96285b749f0ef) in a gist. Does this help?

**Comment by frederickfogerty** [comment]
@samwgoldman I will give that a go, seems like it should work.

**Comment by tcoopman** [comment]
@samwgoldman maybe something for the documentation?

**Comment by jeffutter** [comment]
@samwgoldman Awesome. Thanks for that article it works. Any idea why declaring my own empty module wouldn't work though? Even with the same regex, it doesn't seem to find my module declaration. Personally I would rather have an extra module declaration rather than add another npm dep.

**Comment by samwgoldman** [comment]
@jeffutter Could you provide a repo that has the minimal code+config to reproduce what you're seeing? What you're describing should work, so a repro would help me figure out what's going on.

**Comment by cesarandreu** [comment]
@samwgoldman I avoided adding webpack and setting up its config file, but the following code is exactly what you'd be using with Webpack and css modules.

I'll also note that the example you linked above is working great. I'd vote +1 for adding it to the docs, this was one of the remaining errors I was getting in one of my repos after moving the code to be more flow-friendly.


**package.json**

```json
{
  "name": "flow-css-modules",
  "version": "1.0.0",
  "main": "src/Foo.js",
  "dependencies": {
    "react": "^0.13.3"
  }
}

```

**.flowconfig**

```
[include]
.*/src/.*

[libs]
./interfaces/CSSModule.js

[options]
module.name_mapper='.*\(.css\)' -> 'CSSModule'
module.system=node
strip_root=true
```

**src/Foo.js**

```js
/* @flow */
import cn from './Foo.css'
import type ReactElement from 'react'
import React, { Component } from 'react'

export default class Foo extends Component {
  render (): ReactElement {
    return (
      <div className={cn.Foo}>
        Foo
      </div>
    )
  }
}
```

**src/Foo.css**

```css
.Foo {
  height: 100px;
  width: 100px;
}
```

**interfaces/CSSModule.js**

```js
declare module CSSModule {
  declare var exports: { [key: string]: string };
}

declare module 'CSSModule' {
  declare var exports: { [key: string]: string };
}
```

I tried both of those variations and neither works. However if I change it so it has the same string, it works. For example:

```js
declare module './Foo.css' {
  declare var exports: { [key: string]: string };
}
```

**Comment by briandipalma** [comment]
I'm seeing this error,

```bash
app/main.js:7
  7: import "./main-style.css";
            ^^^^^^^^^^^^^^^^^^ ./main-style.css. Required module not found
```

I guess that means the replacement didn't occur, so there is an issue with the RegExp (`module.name_mapper='^.*.css' -> 'CSSModule'`)?

**Comment by mkatrenik** [comment]
@briandipalma your regex works for me if i set `module.system=haste`

**Comment by briandipalma** [comment]
@mkatrenik 
I eventually went for the `empty/object` trick from one of the linked gists https://github.com/briandipalma/wp-r-template/blob/master/.flowconfig#L12 it works fine.

**Comment by eudisd** [comment]
+1

**Comment by samwgoldman** [comment]
Sorry for the delay here. @cesarandreu thank you for the very clear repro case. I figured out what is going on here, and it seems like a simple oversight.

In an effort to make the issues a bit higher signal, I'm going to close this and replace it with #1322, which is more to the point with the exact issue.

Thanks everyone!

**Comment by faceyspacey** [comment]
but what about when you import files without the extension?
