### ISSUE TITLE
Named import from module `http`. This module has no named export called `Server`.

### ISSUE THREAD

**Issue by akaRem** [facebook/flow#5113]
Having such file 
```
// @flow
import type { Server } from "http";
```
I receive this error on `flow check`
```
Error: src/file.js:2
  2: import type { Server } from "http";
                   ^^^^^^ Named import from module `http`. This module has no named export called `Server`.
```
in the very same time I have declarations for express 4:
```
$ cat ./flow-typed/npm/express_v4.x.x.js | grep 'import type { Server } from "http";'
import type { Server } from "http";
```
And this import should work.
Could you please help with this problem?

node v8.7.0
flow 0.57.2 (global and as flow-bin in project dependencies")

"http" comes from path like this "/private/tmp/flow/flowlib_219bb066/node.js"
I removed caches in /tmp/flow already and it didn't help

**Comment by larkintuckerllc** [comment]
While not an answer, I got closer to finding out the likely source of the trouble through searching and testing.  Looks like there is connection between the existence of the Express 4 flow-typed defn file and the problem; getting rid of the file gets rid of the problem.  Digging deeper is the existence of the line `import type { Server } from "http";` in that file that is triggering the behavior. No idea why this might be happening (I am new to flow myself).

**Comment by larkintuckerllc** [comment]
Last bit on this, spend some time troubleshooting this and found a number of curious things.

1) I can replicate this problem writing my own module and library definition using the http module and exported class Server.
2) I can likewise replicate this problem using the Node.js url module and the exported class URL.
3) In the case of the url module and URL class, I can get things working as expected by NOT importing the URL type in the library definition (somehow Flow is able to resolve the type URL without importing it).
4) Trying the same fix for http module and Server class, I get different behavior; cannot seem to use Server without importing it.
4) Looking at the http module library definition, it is not entirely clear why I can import anything; it does not show any exports.

https://github.com/facebook/flow/blob/v0.61.0/lib/node.js#L1091

**Comment by jwickens** [comment]
can confirm it works fine when using koa

**Comment by chmanie** [comment]
Yep. As soon as you `import { Server }` or `import type { Server }` in the flow-typed library definitions it breaks as mentioned in the first post.

**Comment by rogeriopvl** [comment]
This is related and apparently the cause of the issue: https://github.com/facebook/flow/issues/4198

**Comment by larkintuckerllc** [comment]
Manually applied the suggested fixes in issue listed above to my version of Express' flow-typed definitions and it solved the problems; now have 100% coverage and can now import Server myself again.  Can't say I fully understand the issue; but at least it working.  Looks like the fix is being pushed into the official definitions (is is a feature branch right now).

**Comment by rogeriopvl** [comment]
The fix has been merged https://github.com/flowtype/flow-typed/pull/1767

**Comment by chmanie** [comment]
Sadly this doesn't do the trick for me (or maybe I did something stupid). Here's a repository that reproduces the error:

https://github.com/chmanie/flow-http-server-express

And the build:
https://travis-ci.org/chmanie/flow-http-server-express

Remove the type definitions for express and it works again.

**Comment by michaelhogg** [comment]
@chmanie: I'm experiencing the same error with Flow v0.69.0:

```
Cannot import Server because there is no Server export in http.

     16│ import type { Server as NodeServer } from 'http';  // nodejs.org/api/http.html
```

I can confirm that removing this line from `flow-typed/npm/express_v4.x.x.js` prevents the bug from occurring:

```
import type { Server } from 'http';
```

@rogeriopvl: flowtype/flow-typed#1767 fixes #4198 which is related to this issue but is apparently not the same. The change of return type of `express$Application.listen()` from `Server` to `?Server` doesn't seem to solve this issue.

I found this related comment and PR by @keplersj:

https://github.com/facebook/flow/issues/3685#issuecomment-293489863

> The issue come from the next.js libdef from `flow-typed`. The libdef has a `import type { Component } from 'react';` **outside of a `declare module` block.** The messes up the type checker in a major nearly untraceable way.

In flowtype/flow-typed#775, the `import type { Component } from 'react';` was moved inside `declare module "..." { ... }` which apparently was a successful workaround for the issue.

**Comment by vschoener** [comment]
Got this issue, can't Import `Server` from `http` :/

Pretty sad :(

**Comment by theboyWhoCriedWoolf** [comment]
Has this been resolved?

**Comment by decadent** [comment]
As a workaround: if you're writing libdefs yourself, you can alias the imported type in the libdef, and that will permit importing it in other files. E.g.: `import {IncomingMessage as IncomingMessageType} from 'http';` in your libdef prevents imports of IncomingMessage in other files from failing.

Not sure yet if this will make *similarly aliased* imports fail, but doesn't seem so.

**Comment by goodmind** [comment]
This was fixed by #7448
