### ISSUE TITLE
Feature Suggestion: Filtering types by literal property comparison

### ISSUE THREAD

**Issue by bsmith-cycorp** [facebook/flow#6830]
Suppose I have the following types:
```
type Test = {
  testType: 'single'|'set'
}
type TestSet = Test & {
  testType: 'set',
  setOnlyProperty: string
}
type TestSingle = Test & {
  testType: 'single',
  singleOnlyProperty: string
}
```
It would be very useful to be able to say,
```
var test: Test = ...;
if(testType === 'set') {
  console.log(test.setOnlyProperty);
} else {
  console.log(test.singleOnlyProperty);
}
```
I'd think this would be doable, but I'm not a type-system expert. It also occurs to me now that once the ES pattern-matching syntax comes out this kind of thing would be even more useful, and possibly easier to implement.

**Comment by bsmith-cycorp** [comment]
To better-generalize the use-case, you're sort of up a creek right now if you want to do polymorphism in Flow. If you have a list of objects that you want to operate on, and they can be one of multiple sub-types of a given base type, you can't treat them differently based on their sub-types. In Java you might do:
```java
if(obj instanceof Type1) {
  ...
} else {
  ...
}
```
but Flow is fundamentally different because it leaves behind no runtime artifacts. It does allow you to do something similar with primitives:
```javascript
if(typeof myVal === 'string') {
  ...
} else {
  ...
}
```
which is great. My suggestion above would simply allow the same pattern to be applied to more advanced types, assuming it's feasible to implement.

**Comment by wchargin** [comment]
The example that you propose is unsound. Suppose that we have

```js
const test: Test = {testType: "single"};
```

This of course type-checks. If your code were valid, then we would try
to dereference `singleOnlyProperty`, which does not actually exist on
the object.

For the same reason, this is also valid:

```js
const test: Test = {testType: "single", setOnlyProperty: "wat"};
```

Again, `singleOnlyProperty` does not exist.

The problem is that `Test` is a very “open” type. A `Test` has to have a
`testType`, but it can have any other fields as well, regardless of what
its type is.

It sounds like you actually want to write the following:

```js
// @flow
type Test = TestSet | TestSingle;
type TestSet = {|
  testType: "set",
  setOnlyProperty: string,
|};
type TestSingle = {|
  testType: "single",
  singleOnlyProperty: string
|};
```

I’ve made two changes. First, the `{| … |}` syntax means that the
objects are _exact_: no extra fields are permitted. Second, the `Test`
type is explicitly a union of its valid implementations.

Now, Flow lets you write your function:

```js
function process(test: Test) {
  if (test.testType === "set") {
    console.log(test.setOnlyProperty);
  } else {
    console.log(test.singleOnlyProperty);
  }
}
```

**Comment by wchargin** [comment]
[Here is the whole thing in a Flow-Try.][1]

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagCqYM7KgC8uByAypkQD5mEUCWAdgObSYDcKG2eD1EqADeNRKFDJyOXgC5QAInzUFAGnGhlyAPLNoqAAoAnWFiNp5hIy1bqaAX25os9SjY5DRGqYRlZ5Su6Yahr4Qbr6xqaY5qiWyNZsiA7ciJAArswAxsiMsMyg6CZZBPgAFD7I8vzIAJQiGoyQoBXkAHSVftjEPYpaCvXCGhJZ+fiwHG1wrK2EbVoRhiZmaLXcEvagmNDKDRIjYxOYU7AzlfPhekvRsWsa9ogPQA

**Comment by bsmith-cycorp** [comment]
Ah, so it does. Thanks! As you can probably tell, most of my type system experience comes from OOP languages, so union types are taking a little getting used to.

FWIW, your example also works if I remove the `|`'s in the second and third type definitions.

**Comment by bsmith-cycorp** [comment]
Ah-hah; part of my problem was that I had both the union pattern and the "base type" pattern. So it was actually:
```
type Test = TestSet|TestSingle
type TestBase = {
  testType: 'single'|'set'
}
type TestSet = TestBase & {
  testType: 'set',
  setOnlyProperty: string
}
type TestSingle = TestBase & {
  testType: 'single',
  singleOnlyProperty: string
}
```
It appears the `testType: 'single'|'set'` doesn't simply get "overridden" by `testType: 'set',` and `testType: 'single',`.

**Comment by wchargin** [comment]
> Ah, so it does. Thanks! As you can probably tell, most of my type
> system experience comes from OOP languages, so union types are taking
> a little getting used to.

You’re welcome. You’ll get used to it. :-)

> FWIW, your example also works if I remove the |'s in the second and
> third type definitions.

True, exact types are not always required, but they’re usually what you
want. I use them always unless there’s a good reason not to.
(Sometimes, they solve problems very similar to this one.)

> When I removed the base version of the property, it worked.

When I started using Flow, I also tried to use intersection types in the
way that you’re trying to use them.

Some advice: Don’t. It doesn’t work. They have _lots_ of problems. :-)

(See, for instance, #5895, if you want some more gory details.)

**Comment by wchargin** [comment]
> Woah, I didn't even know type spreading was a thing

Understandable, as it’s not documented directly (though it is mentioned
in the documentation and has been public and recommended for years).

> From reading in the docs about intersection, it seems like the two
> should do the same thing, but they appear to have somewhat different
> behaviors.

Just to say it explicitly: the _intended_ semantics of intersection
types is that if `x: A & B`, then it is valid to say that `x: A` and it
is valid to say that `x: B`. That is, the set of values of `A & B` is
the intersection of the sets of values of `A` and `B`.

> Could you speak more to what the difference is?

I wish that I could. Unfortunately, the docs for intersection types are
simply wrong. The docs for intersection types are wrong. They present a
nice picture of what intersection types _should_ do, but it so happens
that Flow does not implement what is described in the docs.
Consequently, I don’t have a good mental model of how Flow’s
intersection types actually behave.

(For instance, Flow’s intersection types are neither commutative nor
associative. That is, if `x: A & B`, then it is not necessarily the case
that `x: B & A`. And, if `x: A & (B & C)`, then it is not necessarily
the case that `x: (A & B) & C`. That doesn’t sound like any notion of
“intersection” that I’ve ever heard of.)

One thing does make sense: an intersection of exact object types with
distinct sets of fields is uninhabited:

```js
type FreshlyPickedApple = {|+color: string|};
type ProcessedApple = {|+color: string, +weight: number|};
type Wat = FreshlyPickedApple & ProcessedApple;
// There is no `x` such that `x: Wat`:
//   - If `x` has field `weight`, it is incompatible with `FreshlyPickedApple`.
//   - If `x` omits field `weight`, it is incompatible with `ProcessedApple`.
```

As exact object types very often _are_ what you want, it follows that
intersection types of objects very often are _not_ what you want,
independent of the fact that they’re badly broken in other ways.

Type-level object spread also has problems, seems to behave _better_.
Its semantics are what you would expect and what you probably want:
`{...A, moreFields}` means “act as if I had written down all the fields
of `A` right there.” There’s not too much more about it right off the
bat. Perhaps you have some more specific questions or examples?

**Comment by wchargin** [comment]
Apologies for the delay—just noticed your comment.

> Starting to wonder if I should have gone with TypeScript, haha

The main relevant difference for TypeScript is that object types are
exact by default, whereas in Flow they are not.

> Accessing properties from TypeBase causes Flow to complain that they
> could be undefined, even though they can't

This is fixed by making the type exact; see my response to #6855.

> Checking for properties that exist outside of TypeBase, in an effort
> to refine the type

Is it feasible for you to have a single `type` field to use as the
discriminant? [Like this:][sample-type-discriminant]

```js
// @flow
export type OverallType = Type1 | Type2 | Type3;

type TypeBase = {|
  id: string,
  // other attributes removed for brevity
|};

export type Type1 = {|
  ...TypeBase,
  type: "TYPE_1",
|};

export type Type2 = {|
  ...TypeBase,
  type: "TYPE_2",
  args: Array<OverallType>,
|};

export type Type3 = {|
  ...Type2,
  type: "TYPE_3",  // this works even with `...Type2`
  otherStuff: string,
|};

const t1: Type1 = {type: "TYPE_1", id: "ego"};
const t2: Type2 = {type: "TYPE_2", id: "ego", args: [t1, t1]};
const t3: Type3 = {type: "TYPE_3", id: "ego", args: [t1, t2], otherStuff: "OK"};

function process(x: OverallType) {
  switch (x.type) {
    case "TYPE_1":
      (x: Type1);
      break;
    case "TYPE_2":
      (x: Type2);
      break;
    case "TYPE_3":
      (x: Type3);
      break;
    default:
      throw new Error("unknown command type: " + (x.type: empty));
  }
}
```

[sample-type-discriminant]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBTAHgB1gJwC6hwJ7rKgDyAbslgIbTQAqRJAvKI8QIygA+bTATDz7EAzAG5EiQsWHIAQtQDOLUAG9uiUKACWAEwBcoRTizaAdgHMANJtAhQsHAAsqoajhPaARgFccyRVAsZABbWEpdUEhsUC9g8m1CRG4AXwkUDGw8aRJ2ZC5WdVsAOlK8hWUbLRzDACJ6AE0ABQBRAH0OWptU9LRMXHwmWUFCjS1S4vKlZCrB4jrG1rb+LttqLAtFQwBBLBoCAB4KKloGJgA+brTJPqy53KYRUFGSsoFZmtB65vaRLq17M5tIF4NgANaBZCUMygeCJJygAAGEzy-ERtkcLiwAGUcD5IJBDMZTJYrukAMawMzGfAcQx5ApqT7fJadKw6AxfZAWWC1a6U6nZfj0gTPJlMBY-Zb-PR1bm89nrTaGADaOA47PVAF1+VSaTgRCLRGLVMzFr8ZZzavL-kqtqA1Rr8PwtezMVRcfjCV9SABpPnpSA+MzknDaKmgdBYWDkgKKAAUqEMxxodDyAEo1LZFHCcOSEYnijlM6pbFpydMvuaOrV9GWtKBE0b8umJA2G3FkNQwW2GxXlFWpSs6+2tE3hq361pO93e+XKyyLSPR+O8iJJ6PYsFZ-XdMhINQfNAcMv285o-BQGZkJeWntsPHasGwWYEDDKSEQtQzJFmaAANSNqgRYSqAoToIQ6YbqAKSILBQA

**Comment by bsmith-cycorp** [comment]
Unfortunately the {{type}} field that we have for these objects is actually an array of strings. If it were possible to refine by a subset of items in the array then that would be amazing, but it's understandable for that to not be an implemented feature in Flow, given that it's fairly obscure.

I did end up switching to exact types, which helped a bit, but the strange thing is that even with exact types, even if I also remove the de-structuring and copy all the properties into the types directly, Flow still can't refine based on the existence of a property.

**Comment by wchargin** [comment]
> Unfortunately the `type` field that we have for these objects is
> actually an array of strings. If it were possible to refine by a
> subset of items in the array then that would be amazing, but it's
> understandable for that to not be an implemented feature in Flow,
> given that it's fairly obscure.

There’s no way that I know of to refine by a subset of items in an
array, no; I don’t know exactly what that would mean.

> even with exact types, even if I also remove the spreading and copy
> all the properties into the types directly, Flow still can't refine
> based on the existence of a property.

Hmm—I’m having trouble reproducing this, even with spreading. With the
types as in my previous example, [this works for me][try-1]. This also
works [without the `type` field][try-2]. Moreover, this is [a documented
feature][docs], so if it’s genuinely not working then that may be a bug.

You will want to beware of #6488, though (perhaps that’s what you’re
hitting?), which may unfortunately be a show-stopper depending on your
needs.

[try-1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBTAHgB1gJwC6hwJ7rKgDyAbslgIbTQAqRJAvKI8QIygA+bTATDz7EAzAG5EiQsWHIAQtQDOLUAG9uiUKACWAEwBcoRTizaAdgHMANJtAhQsHAAsqoajhPaARgFccyRVAsZABbWEpdUEhsUC9g8m1CRG4AXwkUDGw8aRJ2ZC5WdVsAOlK8hWUbLRzDACJ6AE0ABQBRAH0OWptU9LRMXHwmWUFCjS1S4vKlZCrB4jrG1rb+LttqLAtFQwBBLBoCAB4KKloGJgA+brTJPqy53KYRUFGSsoFZmtB65vaRLq17M5tIF4NgANaBZCUMygeCJJygAAGEzy-ERtkcLiwAGUcD5IJBDMZTJYruldMgAMbQdYkcjrUCoQzHGh0PISbSQUAACgAhKhiutNgBKNS2SmwMzGILISDmZAGWQFRkSFKITk8gVCxSi1TiyXS4JyswKwyooR5J6sVCq9Vc7kCzFUXH4yC6-VSvBG+WKy3PFWINVAA
[try-2]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBTAHgB1gJwC6hwJ7rKgDyAbslgIbTQAqRJAvKI8QIygA+bTATDz7EAzAG5EiQsWHIAQtQDOLUAG9uiUKACWAEwBcoRTizaAdgHMANJtAhQsHAAsqoajhPaARgFccyRVAsZABbWEpdUEhsUC9g8m1CRG4AXwkUDGw8aRJ2ZC5WdVsAOlK8hWUbVPS0TFx8JllBQo0tUuLypWQbLWosC0VDAEEsGgIAHgoqWgYmAD4qtMlarIaZPJFQFpKygR6HZyoAZRwfSEhDY1NLRfTdZABjaD6Scj7QVEMpmjo8iW1IKAABQAQlQxT6AwAlGpbA9YGZjEFkJBzMgDLICh8JClEADgeDIYoYao4QikcFUWZ0YY8oJeBsttjELj8UDwY4XFgTmdICSyYi8JS0RjGaxUDjEEA
[docs]: https://flow.org/en/docs/types/unions/#toc-disjoint-unions-with-exact-types

**Comment by bsmith-cycorp** [comment]
> ...I don’t know exactly what that would mean.

It would be some declarative way of saying "array which contains at least these values". But again, hardly something I would expect to be available.

> Hmm—I’m having trouble reproducing this

Ah-hah. I scrutinized it a little more and I think it might be specific to the optional-chaining and `??` operator. Still a bug, I think, but a more obscure one. Example:
https://flow.org/try/#0PTAEAEDMBsHsHcBQBTAHgB1gJwC6hwJ7rKgAqRyAgtNKALxkUCMoAPo8QEwDciKG2PIWIdkAIQCGAZxIMA3q0ShQASwAmALlBScWFQDsA5gBpErAL580mXPgqiW8xcoB0b8sUkyzl-jaH2Hsic9KAKSqBuLkFeyKYR6pxaOnpGPnwAbhJYoJCwsFoA-EHUtPIJmqAA5HmwVabmvIjQyHgpTMm6BoahtYUu6qCFhdVVvC1tuknaXUa9+f2JQyNVY0A

**Comment by bsmith-cycorp** [comment]
In fact, if you make `foo` non-maybe and you remove the optional chaining operators, the problem persists. So it's more just that Flow doesn't treat `foo.bar ?? ''` the same as `foo.bar ? foo.bar : ''`, which it should if possible.

**Comment by mbernardy** [comment]
The earlier example don't seem to work with destructuring. 

https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagCqYM7KgC8uByAypkQD5mEUCWAdgObSYDcKG2eD1EqADeiUKGTkcvAFygARPmryANGNBLkAeWbRUABQBOsLIbRzmAVwC2AI0yG1AX25os9Si3bZSo8ZMJpLDlFLw5VdXwwzB09IxMHcw1kQy9EF0REEFB4WEMAa3xQSBZMREhLZgBjZEZYZlB0YyqCfAAKAOQ5fmQAShF1RkhQDvIAOk6gn2JSRWV+v3FQKvr8WA4xuFZRwjHNWINjUzRQACpQAEYABl7ucSdQTGglAaXl1fXMTdhtzr3og7xY6oW7qJzpTLZAAmsAIzAA5ERcgVQDI2uVKjU6g0mrAWvh8AAmHZdDwLdQrZiEEQSKS8UAPUidO7iIYjSb0mazTTyclvSlrDZbEl7aiAo6JVBnS43FkPJ4vRbiAWfb6-cZRNgccUJMwguXpIA

It's obviously not a disaster to have to write without using destructuring but it would be nice to be able to given how much it's used elsewhere within our (and I assume other's) code.

Does destructuring generally lose/remove type information and should be avoided with flow?

**Comment by wchargin** [comment]
> The earlier example don't seem to work with destructuring.

Destructuring isn’t the problem. If you desugar the destructuring, [the
problem persists][1]:

```js
// doesn't work :(
function process2(test: Test) {
  const testType = test.testType;
  if (testType === "set") {
    console.log(test.setOnlyProperty * 10);
  } else {
    console.log(test.singleOnlyProperty);
  }
}
```

What you’re observing is that Flow only refines the types of variables;
it does not track complex conditions among _multiple_ variables
(sometimes called “heap refinements”).

> Does destructuring generally lose/remove type information and should
> be avoided with flow?

Attempting to refine based on information that has been aliased in a
different variable, rather than a direct property access, is indeed
unsupported and will not work in general.

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagCqYM7KgC8uByAypkQD5mEUCWAdgObSYDcKG2eD1EqADeiUKGTkcvAFygARPmryANGNBLkAeWbRUABQBOsLIbRzmAVwC2AI0yG1AX25os9Si3bZSo8ZMJpLDlFLw5VdXwwzB09IxMHcw1kQy9EF0REEFB4WEMAa3xQSBZMREhLZgBjZEZYZlB0YyqCfAAKAOQ5fmQAShF1RkhQDvIAOk6gn2JSRWV+v3FQKvr8WA4xuFZRwjHNWINjUzRQACpQAEYABl7ucSdQTGglAaXl1fXMTdhtzr3og7xY6oW7qJzpTLZAAmsAIzAA5ERcgVQDI2uVKjU6g0mrAWvh8AAmHZdDwLdQrZiECRSXhCP6TXh3UBDEaM9wzWaaeTkt6UtYbLYkvbUQFHRKoM6XG7Mh5PF6LcT8z7fX7jKJsDhihJmEGy9JAA
